//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8701")]
        public ushort GSPort {
            get {
                return ((ushort)(this["GSPort"]));
            }
            set {
                this["GSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6678")]
        public ushort TSPort {
            get {
                return ((ushort)(this["TSPort"]));
            }
            set {
                this["TSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public ushort 封包限定数量 {
            get {
                return ((ushort)(this["封包限定数量"]));
            }
            set {
                this["封包限定数量"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public ushort 异常屏蔽时间 {
            get {
                return ((ushort)(this["异常屏蔽时间"]));
            }
            set {
                this["异常屏蔽时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public ushort 掉线判定时间 {
            get {
                return ((ushort)(this["掉线判定时间"]));
            }
            set {
                this["掉线判定时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public byte 游戏OpenLevelCommand {
            get {
                return ((byte)(this["游戏OpenLevelCommand"]));
            }
            set {
                this["游戏OpenLevelCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal 装备特修折扣 {
            get {
                return ((decimal)(this["装备特修折扣"]));
            }
            set {
                this["装备特修折扣"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal 怪物额外爆率 {
            get {
                return ((decimal)(this["怪物额外爆率"]));
            }
            set {
                this["怪物额外爆率"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal 怪物经验倍率 {
            get {
                return ((decimal)(this["怪物经验倍率"]));
            }
            set {
                this["怪物经验倍率"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte 减收益等级差 {
            get {
                return ((byte)(this["减收益等级差"]));
            }
            set {
                this["减收益等级差"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public decimal 收益减少比率 {
            get {
                return ((decimal)(this["收益减少比率"]));
            }
            set {
                this["收益减少比率"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public ushort 怪物诱惑时长 {
            get {
                return ((ushort)(this["怪物诱惑时长"]));
            }
            set {
                this["怪物诱惑时长"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte 物品清理时间 {
            get {
                return ((byte)(this["物品清理时间"]));
            }
            set {
                this["物品清理时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte 物品归属时间 {
            get {
                return ((byte)(this["物品归属时间"]));
            }
            set {
                this["物品归属时间"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database")]
        public string GameData目录 {
            get {
                return ((string)(this["GameData目录"]));
            }
            set {
                this["GameData目录"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Backup")]
        public string 数据备份目录 {
            get {
                return ((string)(this["数据备份目录"]));
            }
            set {
                this["数据备份目录"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte NoobSupportCommand等级 {
            get {
                return ((byte)(this["NoobSupportCommand等级"]));
            }
            set {
                this["NoobSupportCommand等级"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 软件注册代码 {
            get {
                return ((string)(this["软件注册代码"]));
            }
            set {
                this["软件注册代码"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1\t1\tWelcome to the world of Legends Eternal, Legends Eternal is more exciting wit" +
            "h you! ")]
        public string 系统AnnounceText {
            get {
                return ((string)(this["系统AnnounceText"]));
            }
            set {
                this["系统AnnounceText"] = value;
            }
        }
    }
}
